version: '3.8'

services:
  one_more_chance:
    container_name: onemorechance_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
