version: '3.8'

services:
  one_more_chance:
    container_name: onemorechance_app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TURSO_DB_AUTH_TOKEN: ${TURSO_DB_AUTH_TOKEN}
        TURSO_DB_URL: ${TURSO_DB_URL}
    restart: always
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
