name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "app/src/**"
      - ".github/workflows/ci.yml"
    
env:
  APP_NAME: onemorechance
  RUNS_ON: ubuntu-22.04

jobs:
  build_and_push:
    runs-on: $RUNS_ON
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/$APP_NAME:latest

  compose-up:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH into server, pull and restart app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /www/omc/
            docker compose -f omc.docker-compose.yml up -d