name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "app/**"
      - ".github/workflows/ci.yml"

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  gitleaks:
    uses: jd-apprentice/jd-workflows/.github/workflows/gitleaks.yml@main
    with:
      runs-on: ubuntu-latest
      name: Gitleaks
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}

  codacy_scan:
    uses: jd-apprentice/jd-workflows/.github/workflows/codacy.yml@main
    needs: gitleaks
    with:
      runs-on: ubuntu-latest
      name: Codacy
    secrets:
      project_token: ${{ secrets.CODACY_PROJECT_TOKEN }}

  build_and_push:
    runs-on: ubuntu-22.04
    needs: [gitleaks, codacy_scan]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2
        with:
          args: --build-arg="TURSO_DB_AUTH_TOKEN=${{ secrets.TURSO_DB_AUTH_TOKEN }}" --build-arg="TURSO_DB_URL=${{ secrets.TURSO_DB_URL }}"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/onemorechance:latest

  render_deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: use curl to trigger the render deploy hook
        run: |
          curl -X GET https://api.render.com/deploy/${{ secrets.RENDER_HOOK_URL }}
