name: Deploy Manually

on:
  workflow_dispatch:

jobs:
  render_deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: use curl to trigger the Render deploy hook
        run: |
          curl -X GET https://api.render.com/deploy/{{ secrets.RENDER_HOOK_URL }}
