name: Deploy Manually

on:
  workflow_dispatch:

jobs:
  develop:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: use curl to trigger the Render deploy hook
        run: |
          curl -X GET https://api.render.com/deploy/${{ secrets.RENDER_HOOK_URL_DEVELOP }}

  prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: use curl to trigger the Render deploy hook
        run: |
          curl -X GET https://api.render.com/deploy/${{ secrets.RENDER_HOOK_URL }}
